#!/usr/bin/env python3
"""
==============================================================================
ML COMPARISON - Compare Different ML Frameworks for Motion Detection
==============================================================================

This script trains and compares multiple ML approaches:
1. Pure Python (runs on Pico)
2. scikit-learn (PC baseline)
3. TensorFlow/TFLite (for TinyML deployment)
4. Export for Edge Impulse

USAGE:
    python ml_compare.py training_data.csv

OUTPUT:
    - Accuracy comparison table
    - Confusion matrices
    - Exported models for Pico deployment
    - TFLite model for microcontroller
    - Edge Impulse compatible CSV

==============================================================================
"""

import sys
import csv
import math
import random
import json
from collections import Counter
from pathlib import Path

# Class labels
CLASS_NAMES = ['STOP', 'FWD', 'BWD', 'T_L', 'T_R', 'PUSH']
NUM_CLASSES = 6


# ==============================================================================
# DATA LOADING
# ==============================================================================

def load_data(filename):
    """Load training data from CSV."""
    X, y = [], []
    feature_names = None

    with open(filename, 'r') as f:
        reader = csv.reader(f)
        header = next(reader)
        feature_names = header[:-2]  # Exclude 'label' and 'label_name'

        for row in reader:
            if len(row) < 3:
                continue
            features = [float(x) for x in row[:-2]]
            label = int(row[-2])
            X.append(features)
            y.append(label)

    print(f"Loaded {len(X)} samples, {len(feature_names)} features")
    print(f"Features: {', '.join(feature_names)}")

    # Class distribution
    counts = Counter(y)
    print("\nClass distribution:")
    for label in sorted(counts.keys()):
        pct = 100 * counts[label] / len(y)
        bar = '#' * int(pct / 2)
        print(f"  {CLASS_NAMES[label]:6s}: {counts[label]:4d} ({pct:5.1f}%) {bar}")

    return X, y, feature_names


def split_data(X, y, test_ratio=0.2, seed=42):
    """Split into train/test sets."""
    random.seed(seed)
    indices = list(range(len(X)))
    random.shuffle(indices)

    split = int(len(indices) * (1 - test_ratio))
    train_idx, test_idx = indices[:split], indices[split:]

    X_train = [X[i] for i in train_idx]
    y_train = [y[i] for i in train_idx]
    X_test = [X[i] for i in test_idx]
    y_test = [y[i] for i in test_idx]

    return X_train, X_test, y_train, y_test


def normalize_data(X_train, X_test):
    """Normalize features (z-score)."""
    n_features = len(X_train[0])

    means = [sum(x[i] for x in X_train) / len(X_train) for i in range(n_features)]
    stds = [math.sqrt(sum((x[i] - means[i])**2 for x in X_train) / len(X_train)) or 1.0
            for i in range(n_features)]

    X_train_norm = [[(x[i] - means[i]) / stds[i] for i in range(n_features)] for x in X_train]
    X_test_norm = [[(x[i] - means[i]) / stds[i] for i in range(n_features)] for x in X_test]

    return X_train_norm, X_test_norm, means, stds


# ==============================================================================
# 1. PURE PYTHON MODELS (Pico-compatible)
# ==============================================================================

class PythonKNN:
    """K-Nearest Neighbors - pure Python, runs on Pico."""

    def __init__(self, k=5):
        self.k = k
        self.X_train = []
        self.y_train = []

    def fit(self, X, y):
        self.X_train = [x[:] for x in X]
        self.y_train = y[:]

    def predict(self, X):
        predictions = []
        for x in X:
            distances = []
            for i, train_x in enumerate(self.X_train):
                dist = math.sqrt(sum((a - b)**2 for a, b in zip(x, train_x)))
                distances.append((dist, self.y_train[i]))
            distances.sort()
            k_nearest = distances[:self.k]
            votes = Counter(label for _, label in k_nearest)
            predictions.append(votes.most_common(1)[0][0])
        return predictions

    def export_micropython(self, means, stds, filename='knn_model.py'):
        """Export for MicroPython."""
        code = f'''"""KNN Model - Generated by ml_compare.py"""

K = {self.k}
MEANS = {means}
STDS = {stds}
X_TRAIN = {self.X_train[:50]}  # Limited for memory
Y_TRAIN = {self.y_train[:50]}

def normalize(x):
    return [(x[i] - MEANS[i]) / STDS[i] for i in range(len(x))]

def predict(x):
    x_norm = normalize(x)
    distances = []
    for i, tx in enumerate(X_TRAIN):
        dist = sum((a - b)**2 for a, b in zip(x_norm, tx)) ** 0.5
        distances.append((dist, Y_TRAIN[i]))
    distances.sort()
    votes = {{}}
    for _, label in distances[:K]:
        votes[label] = votes.get(label, 0) + 1
    return max(votes, key=votes.get)
'''
        with open(filename, 'w') as f:
            f.write(code)
        print(f"  Exported: {filename}")


class PythonNN:
    """Simple Neural Network - pure Python, runs on Pico."""

    def __init__(self, input_size, hidden_size=10, output_size=6, lr=0.01):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.lr = lr

        # Initialize weights
        scale1 = math.sqrt(2.0 / input_size)
        scale2 = math.sqrt(2.0 / hidden_size)

        self.W1 = [[random.gauss(0, scale1) for _ in range(input_size)]
                   for _ in range(hidden_size)]
        self.b1 = [0.0] * hidden_size
        self.W2 = [[random.gauss(0, scale2) for _ in range(hidden_size)]
                   for _ in range(output_size)]
        self.b2 = [0.0] * output_size

    def _relu(self, x):
        return max(0, x)

    def _softmax(self, x):
        max_x = max(x)
        exp_x = [math.exp(xi - max_x) for xi in x]
        sum_exp = sum(exp_x)
        return [e / sum_exp for e in exp_x]

    def _forward(self, x):
        h = [self._relu(self.b1[i] + sum(self.W1[i][j] * x[j]
             for j in range(self.input_size))) for i in range(self.hidden_size)]
        o = [self.b2[i] + sum(self.W2[i][j] * h[j]
             for j in range(self.hidden_size)) for i in range(self.output_size)]
        return h, self._softmax(o)

    def fit(self, X, y, epochs=100):
        for epoch in range(epochs):
            indices = list(range(len(X)))
            random.shuffle(indices)
            correct = 0

            for idx in indices:
                x, label = X[idx], y[idx]
                h, out = self._forward(x)

                if out.index(max(out)) == label:
                    correct += 1

                # Backprop
                d_out = out[:]
                d_out[label] -= 1

                for i in range(self.output_size):
                    for j in range(self.hidden_size):
                        self.W2[i][j] -= self.lr * d_out[i] * h[j]
                    self.b2[i] -= self.lr * d_out[i]

                d_h = [sum(self.W2[i][j] * d_out[i] for i in range(self.output_size))
                       for j in range(self.hidden_size)]

                for i in range(self.hidden_size):
                    if h[i] > 0:  # ReLU derivative
                        for j in range(self.input_size):
                            self.W1[i][j] -= self.lr * d_h[i] * x[j]
                        self.b1[i] -= self.lr * d_h[i]

            if (epoch + 1) % 20 == 0:
                acc = 100 * correct / len(X)
                print(f"    Epoch {epoch+1}: {acc:.1f}%")

    def predict(self, X):
        return [self._forward(x)[1].index(max(self._forward(x)[1])) for x in X]

    def export_micropython(self, means, stds, filename='nn_model.py'):
        """Export for MicroPython."""
        code = f'''"""Neural Network Model - Generated by ml_compare.py"""
import math

MEANS = {means}
STDS = {stds}
W1 = {[[round(w, 6) for w in row] for row in self.W1]}
b1 = {[round(b, 6) for b in self.b1]}
W2 = {[[round(w, 6) for w in row] for row in self.W2]}
b2 = {[round(b, 6) for b in self.b2]}

def normalize(x):
    return [(x[i] - MEANS[i]) / STDS[i] for i in range(len(x))]

def relu(x):
    return max(0, x)

def predict(x):
    x = normalize(x)
    h = [relu(b1[i] + sum(W1[i][j] * x[j] for j in range({self.input_size})))
         for i in range({self.hidden_size})]
    o = [b2[i] + sum(W2[i][j] * h[j] for j in range({self.hidden_size}))
         for i in range({self.output_size})]
    return o.index(max(o))
'''
        with open(filename, 'w') as f:
            f.write(code)
        print(f"  Exported: {filename}")


class PythonDecisionTree:
    """Decision Tree - pure Python, runs on Pico."""

    def __init__(self, max_depth=5):
        self.max_depth = max_depth
        self.tree = None

    def _gini(self, y):
        if not y:
            return 0
        counts = Counter(y)
        n = len(y)
        return 1 - sum((c/n)**2 for c in counts.values())

    def _best_split(self, X, y):
        best_gain, best_feat, best_thresh = -1, None, None
        current_gini = self._gini(y)

        for feat in range(len(X[0])):
            values = sorted(set(x[feat] for x in X))
            for i in range(len(values) - 1):
                thresh = (values[i] + values[i+1]) / 2
                left_y = [y[j] for j, x in enumerate(X) if x[feat] <= thresh]
                right_y = [y[j] for j, x in enumerate(X) if x[feat] > thresh]

                if not left_y or not right_y:
                    continue

                gain = current_gini - (len(left_y)/len(y) * self._gini(left_y) +
                                       len(right_y)/len(y) * self._gini(right_y))
                if gain > best_gain:
                    best_gain, best_feat, best_thresh = gain, feat, thresh

        return best_feat, best_thresh

    def _build(self, X, y, depth):
        if depth >= self.max_depth or len(set(y)) == 1 or len(X) < 5:
            return {'leaf': True, 'class': Counter(y).most_common(1)[0][0]}

        feat, thresh = self._best_split(X, y)
        if feat is None:
            return {'leaf': True, 'class': Counter(y).most_common(1)[0][0]}

        left_X = [X[i] for i in range(len(X)) if X[i][feat] <= thresh]
        left_y = [y[i] for i in range(len(X)) if X[i][feat] <= thresh]
        right_X = [X[i] for i in range(len(X)) if X[i][feat] > thresh]
        right_y = [y[i] for i in range(len(X)) if X[i][feat] > thresh]

        return {
            'leaf': False, 'feature': feat, 'threshold': thresh,
            'left': self._build(left_X, left_y, depth + 1),
            'right': self._build(right_X, right_y, depth + 1)
        }

    def fit(self, X, y):
        self.tree = self._build(X, y, 0)

    def _predict_one(self, x, node):
        if node['leaf']:
            return node['class']
        if x[node['feature']] <= node['threshold']:
            return self._predict_one(x, node['left'])
        return self._predict_one(x, node['right'])

    def predict(self, X):
        return [self._predict_one(x, self.tree) for x in X]

    def export_micropython(self, means, stds, filename='tree_model.py'):
        """Export as if-else chain for MicroPython."""

        def tree_to_code(node, indent="    "):
            if node['leaf']:
                return f"{indent}return {node['class']}"
            code = f"{indent}if x[{node['feature']}] <= {node['threshold']:.6f}:\n"
            code += tree_to_code(node['left'], indent + "    ") + "\n"
            code += f"{indent}else:\n"
            code += tree_to_code(node['right'], indent + "    ")
            return code

        code = f'''"""Decision Tree Model - Generated by ml_compare.py"""

MEANS = {means}
STDS = {stds}

def normalize(x):
    return [(x[i] - MEANS[i]) / STDS[i] for i in range(len(x))]

def predict(x):
    x = normalize(x)
{tree_to_code(self.tree)}
'''
        with open(filename, 'w') as f:
            f.write(code)
        print(f"  Exported: {filename}")


# ==============================================================================
# 2. SCIKIT-LEARN MODELS (PC baseline)
# ==============================================================================

def train_sklearn(X_train, X_test, y_train, y_test):
    """Train scikit-learn models for comparison."""
    try:
        from sklearn.neighbors import KNeighborsClassifier
        from sklearn.tree import DecisionTreeClassifier
        from sklearn.ensemble import RandomForestClassifier
        from sklearn.neural_network import MLPClassifier
        from sklearn.svm import SVC
        from sklearn.metrics import accuracy_score
    except ImportError:
        print("  scikit-learn not installed, skipping...")
        return {}

    results = {}
    models = {
        'sklearn_KNN': KNeighborsClassifier(n_neighbors=5),
        'sklearn_Tree': DecisionTreeClassifier(max_depth=5),
        'sklearn_Forest': RandomForestClassifier(n_estimators=10, max_depth=5),
        'sklearn_MLP': MLPClassifier(hidden_layer_sizes=(10,), max_iter=500, random_state=42),
        'sklearn_SVM': SVC(kernel='rbf', random_state=42),
    }

    for name, model in models.items():
        model.fit(X_train, y_train)
        pred = model.predict(X_test)
        acc = accuracy_score(y_test, pred)
        results[name] = acc
        print(f"  {name}: {acc*100:.1f}%")

    return results


# ==============================================================================
# 3. TENSORFLOW / TFLITE (for TinyML)
# ==============================================================================

def train_tensorflow(X_train, X_test, y_train, y_test, output_dir='.'):
    """Train TensorFlow model and convert to TFLite."""
    try:
        import tensorflow as tf
        import numpy as np
    except ImportError:
        print("  TensorFlow not installed, skipping...")
        return None

    # Convert to numpy
    X_train_np = np.array(X_train, dtype=np.float32)
    X_test_np = np.array(X_test, dtype=np.float32)
    y_train_np = np.array(y_train, dtype=np.int32)
    y_test_np = np.array(y_test, dtype=np.int32)

    # Build model
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(16, activation='relu', input_shape=(X_train_np.shape[1],)),
        tf.keras.layers.Dense(8, activation='relu'),
        tf.keras.layers.Dense(NUM_CLASSES, activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    print("  Training TensorFlow model...")
    model.fit(X_train_np, y_train_np, epochs=50, batch_size=32,
              validation_split=0.1, verbose=0)

    # Evaluate
    loss, acc = model.evaluate(X_test_np, y_test_np, verbose=0)
    print(f"  TensorFlow: {acc*100:.1f}%")

    # Save full model
    model.save(f'{output_dir}/motion_model.keras')
    print(f"  Saved: {output_dir}/motion_model.keras")

    # Convert to TFLite
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_types = [tf.float16]
    tflite_model = converter.convert()

    tflite_path = f'{output_dir}/motion_model.tflite'
    with open(tflite_path, 'wb') as f:
        f.write(tflite_model)
    print(f"  Saved: {tflite_path} ({len(tflite_model)} bytes)")

    # Generate C header for embedded deployment
    generate_tflite_header(tflite_model, f'{output_dir}/motion_model.h')

    return acc


def generate_tflite_header(tflite_model, filename):
    """Generate C header file for TFLite model."""
    with open(filename, 'w') as f:
        f.write('// TFLite model for motion detection\n')
        f.write('// Generated by ml_compare.py\n\n')
        f.write(f'const unsigned int motion_model_len = {len(tflite_model)};\n')
        f.write('const unsigned char motion_model[] = {\n  ')

        for i, byte in enumerate(tflite_model):
            f.write(f'0x{byte:02x}')
            if i < len(tflite_model) - 1:
                f.write(', ')
                if (i + 1) % 12 == 0:
                    f.write('\n  ')

        f.write('\n};\n')
    print(f"  Saved: {filename}")


# ==============================================================================
# 4. EDGE IMPULSE EXPORT
# ==============================================================================

def export_edge_impulse(X, y, feature_names, filename='edge_impulse_data.csv'):
    """Export data in Edge Impulse format."""
    with open(filename, 'w') as f:
        # Edge Impulse expects: timestamp, features..., label
        header = ['timestamp'] + feature_names + ['label']
        f.write(','.join(header) + '\n')

        for i, (features, label) in enumerate(zip(X, y)):
            timestamp = i * 20  # Assume 50Hz = 20ms intervals
            row = [str(timestamp)] + [f'{v:.6f}' for v in features] + [CLASS_NAMES[label]]
            f.write(','.join(row) + '\n')

    print(f"  Exported for Edge Impulse: {filename}")
    print("  Upload to Edge Impulse Studio for cloud training")


# ==============================================================================
# EVALUATION
# ==============================================================================

def evaluate(model, X_test, y_test, name):
    """Evaluate model and return accuracy."""
    pred = model.predict(X_test)
    correct = sum(p == t for p, t in zip(pred, y_test))
    acc = correct / len(y_test)
    print(f"  {name}: {acc*100:.1f}%")
    return acc


def confusion_matrix(y_true, y_pred):
    """Print confusion matrix."""
    matrix = [[0] * NUM_CLASSES for _ in range(NUM_CLASSES)]
    for t, p in zip(y_true, y_pred):
        matrix[t][p] += 1

    print("\nConfusion Matrix:")
    print("       " + "  ".join(f"{n:>5s}" for n in CLASS_NAMES))
    for i, row in enumerate(matrix):
        print(f"{CLASS_NAMES[i]:6s} " + "  ".join(f"{v:>5d}" for v in row))


# ==============================================================================
# MAIN
# ==============================================================================

def main():
    if len(sys.argv) < 2:
        print("Usage: python ml_compare.py <training_data.csv>")
        print("\nCollect training data using host.py:")
        print("  1. Run host.py with robot streaming IMU")
        print("  2. Press 'T' to start training mode")
        print("  3. Press 0-5 to select class, perform movement")
        print("  4. Press 'X' to export training data")
        sys.exit(1)

    # Load data
    print("\n" + "=" * 60)
    print("LOADING DATA")
    print("=" * 60)
    X, y, feature_names = load_data(sys.argv[1])

    # Split and normalize
    X_train, X_test, y_train, y_test = split_data(X, y)
    X_train_norm, X_test_norm, means, stds = normalize_data(X_train, X_test)
    print(f"\nTrain: {len(X_train)}, Test: {len(X_test)}")

    # Create output directory
    output_dir = Path('ml_models')
    output_dir.mkdir(exist_ok=True)

    results = {}

    # ==================================================
    # Pure Python models (Pico-compatible)
    # ==================================================
    print("\n" + "=" * 60)
    print("PURE PYTHON MODELS (Pico-compatible)")
    print("=" * 60)

    # KNN
    knn = PythonKNN(k=5)
    knn.fit(X_train_norm, y_train)
    results['Python_KNN'] = evaluate(knn, X_test_norm, y_test, 'KNN (k=5)')
    knn.export_micropython(means, stds, f'{output_dir}/knn_model.py')

    # Decision Tree
    tree = PythonDecisionTree(max_depth=5)
    tree.fit(X_train_norm, y_train)
    results['Python_Tree'] = evaluate(tree, X_test_norm, y_test, 'Decision Tree')
    tree.export_micropython(means, stds, f'{output_dir}/tree_model.py')

    # Neural Network
    nn = PythonNN(len(X_train[0]), hidden_size=10, output_size=NUM_CLASSES)
    print("  Training Neural Network...")
    nn.fit(X_train_norm, y_train, epochs=100)
    results['Python_NN'] = evaluate(nn, X_test_norm, y_test, 'Neural Network')
    nn.export_micropython(means, stds, f'{output_dir}/nn_model.py')

    # ==================================================
    # scikit-learn (PC baseline)
    # ==================================================
    print("\n" + "=" * 60)
    print("SCIKIT-LEARN MODELS (PC baseline)")
    print("=" * 60)
    sklearn_results = train_sklearn(X_train_norm, X_test_norm, y_train, y_test)
    results.update(sklearn_results)

    # ==================================================
    # TensorFlow / TFLite
    # ==================================================
    print("\n" + "=" * 60)
    print("TENSORFLOW / TFLITE (TinyML)")
    print("=" * 60)
    tf_acc = train_tensorflow(X_train_norm, X_test_norm, y_train, y_test, str(output_dir))
    if tf_acc:
        results['TensorFlow'] = tf_acc

    # ==================================================
    # Edge Impulse export
    # ==================================================
    print("\n" + "=" * 60)
    print("EDGE IMPULSE EXPORT")
    print("=" * 60)
    export_edge_impulse(X, y, feature_names, f'{output_dir}/edge_impulse_data.csv')

    # ==================================================
    # Results summary
    # ==================================================
    print("\n" + "=" * 60)
    print("RESULTS SUMMARY")
    print("=" * 60)
    print(f"{'Model':<20s} {'Accuracy':>10s} {'Pico?':>8s}")
    print("-" * 40)
    for name, acc in sorted(results.items(), key=lambda x: -x[1]):
        pico = 'Yes' if name.startswith('Python') else 'No'
        if name == 'TensorFlow':
            pico = 'TFLite'
        print(f"{name:<20s} {acc*100:>9.1f}% {pico:>8s}")

    print("\n" + "=" * 60)
    print("EXPORTED FILES")
    print("=" * 60)
    print(f"  {output_dir}/knn_model.py     - KNN for MicroPython")
    print(f"  {output_dir}/tree_model.py    - Decision Tree for MicroPython")
    print(f"  {output_dir}/nn_model.py      - Neural Network for MicroPython")
    if tf_acc:
        print(f"  {output_dir}/motion_model.tflite - TFLite model")
        print(f"  {output_dir}/motion_model.h      - C header for embedded")
    print(f"  {output_dir}/edge_impulse_data.csv - For Edge Impulse Studio")

    # Confusion matrix for best model
    print("\n" + "=" * 60)
    print("CONFUSION MATRIX (Neural Network)")
    print("=" * 60)
    nn_pred = nn.predict(X_test_norm)
    confusion_matrix(y_test, nn_pred)


if __name__ == '__main__':
    main()
